import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "antd/es/layout/layout";
import { Layout, Menu } from "antd";
import Link from "next/link";
const items = [
  { key: "home", label: <Link href={"/"}>home</Link> },
  { key: "about", label: <Link href={"/"}>about</Link> },
];

export const metadata: Metadata = {
  title: "berita bitcoin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <Header className="flex justify-between">
            <div>
              <h1 className="text-white font-impact font-bold text-[1.5rem] uppercase">
                Berita Bitcoin
              </h1>
            </div>
            <Menu
              theme="dark"
              mode="horizontal"
              defaultSelectedKeys={["2"]}
              items={items}
              style={{ flex: 1, minWidth: 0 }}
              className="justify-end"
            />
          </Header>

          {children}

          <Footer style={{ textAlign: "center" }}>
            Andika ©{new Date().getFullYear()}
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
